# 错误提示不好，会导致误解，如修改 integer 为 interger 可以看到迷惑的报错

swagger: "2.0"

info:
  version: 1.0.0
  title: Simple ApI
  description: A simple api to learn how to write openApi specification

schemes:
  - https

host: simple.api
basePath: /openapi101

paths:
  /persons:
    get:
      summary: Get some persons
      description: Returns a list containing all persons. The list supports paging

      parameters:
        - name: pageSize
          in: query
          description: Number of persons returned
          type: integer
        - name: pageNumber
          in: query
          description: Page Number
          type: integer
      
      responses:
        200:
          description: A list of Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string

# START #####################################################################
    post:
      summary: Create a person
      description: Adds a person to the persons list.

      parameters:
        - name: person
          in: body
          description: The person to create
          schema:
            required: 
              - username

            properties:
              firstName:
                type: string
              lastName:
                type: string
              username:
                type: string

      responses:
        204:
          description: Persons sucesfully created

        400:
          description: persons counld't have been created
#  END  #####################################################################

  /persons/{username}:
    get:
      summary: Get a person
      description: Returns a signal person for its username

      parameters:
        - name: username
          in: path
          required: true
          description: The person's username
          type: string
      responses:
        200:
          description: A Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string

        404:
          description: The Person does not exists